### PR TITLE
Add trademark question

### PR DESCRIPTION
**Pull request by ianbjacobs**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Sorry, trademark of what?

**Comment by adamroach** [comment]
I believe the issue is that "Visa" is a trademark of Visa, "MasterCard" is a trademark of MasterCard, and so on. Given that we need to refer to credit card networks by some identifier, and the only sensible identifiers are aggressively protected trademarks of other organizations, what are our legal obligations here? Do we need a disclaimer of some kind (e.g., indicating non-endorsement and non-ownership)? Do we need explicit permission from the trademark holders? In the U.S., the current formulation in the document is (to my knowledge) explicitly permitted by the doctrine of nominative use, but I don't know how that plays out worldwide.

I assume W3C has staff counsel. I propose this issue be referred to them.

**Comment by marcoscaceres** [comment]
Thanks for the clarification, @adamroach! Definitely sounds like something for @rigow to look at.

**Comment by ianbjacobs** [comment]
I will follow up with W3C legal (and possibly elsewhere).

**Pull request merged**
